set(headers
  vesDataConversionTools.h
  vesKiwiAnimationRepresentation.h
  vesKiwiBaseApp.h
  vesKiwiBrainAtlasRepresentation.h
  vesKiwiDataLoader.h
  vesKiwiDataRepresentation.h
  vesKiwiImagePlaneDataRepresentation.h
  vesKiwiImageWidgetRepresentation.h
  vesKiwiPlaneWidget.h
  vesKiwiPolyDataRepresentation.h
  vesKiwiText2DRepresentation.h
  vesKiwiViewerApp.h
  vesKiwiWidgetRepresentation.h
  )

set(header_dirs
  .
  )
