set(headers

  Array
  Cholesky
  Core
  Dense
  Eigen
  Eigen2Support
  Eigenvalues
  Geometry
  Householder
  Jacobi
  LeastSquares
  LU
  QR
  QtAlignedMalloc
  Sparse
  StdDeque
  StdList
  StdVector
  SVD

  src/Cholesky/LDLT.h
  src/Cholesky/LLT.h
  src/Core/arch/AltiVec/Complex.h
  src/Core/arch/AltiVec/PacketMath.h
  src/Core/arch/Default/Settings.h
  src/Core/arch/NEON/Complex.h
  src/Core/arch/NEON/PacketMath.h
  src/Core/arch/SSE/Complex.h
  src/Core/arch/SSE/MathFunctions.h
  src/Core/arch/SSE/PacketMath.h
  src/Core/ArrayBase.h
  src/Core/Array.h
  src/Core/ArrayWrapper.h
  src/Core/Assign.h
  src/Core/BandMatrix.h
  src/Core/Block.h
  src/Core/BooleanRedux.h
  src/Core/CommaInitializer.h
  src/Core/CwiseBinaryOp.h
  src/Core/CwiseNullaryOp.h
  src/Core/CwiseUnaryOp.h
  src/Core/CwiseUnaryView.h
  src/Core/DenseBase.h
  src/Core/DenseCoeffsBase.h
  src/Core/DenseStorage.h
  src/Core/Diagonal.h
  src/Core/DiagonalMatrix.h
  src/Core/DiagonalProduct.h
  src/Core/Dot.h
  src/Core/EigenBase.h
  src/Core/Flagged.h
  src/Core/ForceAlignedAccess.h
  src/Core/Functors.h
  src/Core/Fuzzy.h
  src/Core/GenericPacketMath.h
  src/Core/GlobalFunctions.h
  src/Core/IO.h
  src/Core/MapBase.h
  src/Core/Map.h
  src/Core/MathFunctions.h
  src/Core/MatrixBase.h
  src/Core/Matrix.h
  src/Core/NestByValue.h
  src/Core/NoAlias.h
  src/Core/NumTraits.h
  src/Core/PermutationMatrix.h
  src/Core/PlainObjectBase.h
  src/Core/ProductBase.h
  src/Core/Product.h
  src/Core/products/CoeffBasedProduct.h
  src/Core/products/GeneralBlockPanelKernel.h
  src/Core/products/GeneralMatrixMatrix.h
  src/Core/products/GeneralMatrixMatrixTriangular.h
  src/Core/products/GeneralMatrixVector.h
  src/Core/products/Parallelizer.h
  src/Core/products/SelfadjointMatrixMatrix.h
  src/Core/products/SelfadjointMatrixVector.h
  src/Core/products/SelfadjointProduct.h
  src/Core/products/SelfadjointRank2Update.h
  src/Core/products/TriangularMatrixMatrix.h
  src/Core/products/TriangularMatrixVector.h
  src/Core/products/TriangularSolverMatrix.h
  src/Core/products/TriangularSolverVector.h
  src/Core/Random.h
  src/Core/Redux.h
  src/Core/Replicate.h
  src/Core/ReturnByValue.h
  src/Core/Reverse.h
  src/Core/Select.h
  src/Core/SelfAdjointView.h
  src/Core/SelfCwiseBinaryOp.h
  src/Core/SolveTriangular.h
  src/Core/StableNorm.h
  src/Core/Stride.h
  src/Core/Swap.h
  src/Core/Transpose.h
  src/Core/Transpositions.h
  src/Core/TriangularMatrix.h
  src/Core/util/BlasUtil.h
  src/Core/util/Constants.h
  src/Core/util/DisableStupidWarnings.h
  src/Core/util/ForwardDeclarations.h
  src/Core/util/Macros.h
  src/Core/util/Memory.h
  src/Core/util/Meta.h
  src/Core/util/ReenableStupidWarnings.h
  src/Core/util/StaticAssert.h
  src/Core/util/XprHelper.h
  src/Core/VectorBlock.h
  src/Core/VectorwiseOp.h
  src/Core/Visitor.h
  src/Eigen2Support/Block.h
  src/Eigen2Support/Cwise.h
  src/Eigen2Support/CwiseOperators.h
  src/Eigen2Support/Geometry/AlignedBox.h
  src/Eigen2Support/Geometry/All.h
  src/Eigen2Support/Geometry/AngleAxis.h
  src/Eigen2Support/Geometry/Hyperplane.h
  src/Eigen2Support/Geometry/ParametrizedLine.h
  src/Eigen2Support/Geometry/Quaternion.h
  src/Eigen2Support/Geometry/Rotation2D.h
  src/Eigen2Support/Geometry/RotationBase.h
  src/Eigen2Support/Geometry/Scaling.h
  src/Eigen2Support/Geometry/Transform.h
  src/Eigen2Support/Geometry/Translation.h
  src/Eigen2Support/Lazy.h
  src/Eigen2Support/LeastSquares.h
  src/Eigen2Support/LU.h
  src/Eigen2Support/Macros.h
  src/Eigen2Support/MathFunctions.h
  src/Eigen2Support/Memory.h
  src/Eigen2Support/Meta.h
  src/Eigen2Support/Minor.h
  src/Eigen2Support/QR.h
  src/Eigen2Support/SVD.h
  src/Eigen2Support/TriangularSolver.h
  src/Eigen2Support/VectorBlock.h
  src/Eigenvalues/ComplexEigenSolver.h
  src/Eigenvalues/ComplexSchur.h
  src/Eigenvalues/EigenSolver.h
  src/Eigenvalues/EigenvaluesCommon.h
  src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h
  src/Eigenvalues/HessenbergDecomposition.h
  src/Eigenvalues/MatrixBaseEigenvalues.h
  src/Eigenvalues/RealSchur.h
  src/Eigenvalues/SelfAdjointEigenSolver.h
  src/Eigenvalues/Tridiagonalization.h
  src/Geometry/AlignedBox.h
  src/Geometry/AngleAxis.h
  src/Geometry/arch/Geometry_SSE.h
  src/Geometry/EulerAngles.h
  src/Geometry/Homogeneous.h
  src/Geometry/Hyperplane.h
  src/Geometry/OrthoMethods.h
  src/Geometry/ParametrizedLine.h
  src/Geometry/Quaternion.h
  src/Geometry/Rotation2D.h
  src/Geometry/RotationBase.h
  src/Geometry/Scaling.h
  src/Geometry/Transform.h
  src/Geometry/Translation.h
  src/Geometry/Umeyama.h
  src/Householder/BlockHouseholder.h
  src/Householder/Householder.h
  src/Householder/HouseholderSequence.h
  src/Jacobi/Jacobi.h
  src/LU/arch/Inverse_SSE.h
  src/LU/Determinant.h
  src/LU/FullPivLU.h
  src/LU/Inverse.h
  src/LU/PartialPivLU.h
  src/misc/Image.h
  src/misc/Kernel.h
  src/misc/Solve.h
  src/plugins/ArrayCwiseBinaryOps.h
  src/plugins/ArrayCwiseUnaryOps.h
  src/plugins/BlockMethods.h
  src/plugins/CommonCwiseBinaryOps.h
  src/plugins/CommonCwiseUnaryOps.h
  src/plugins/MatrixCwiseBinaryOps.h
  src/plugins/MatrixCwiseUnaryOps.h
  src/QR/ColPivHouseholderQR.h
  src/QR/FullPivHouseholderQR.h
  src/QR/HouseholderQR.h
  src/Sparse/AmbiVector.h
  src/Sparse/CompressedStorage.h
  src/Sparse/CoreIterators.h
  src/Sparse/DynamicSparseMatrix.h
  src/Sparse/MappedSparseMatrix.h
  src/Sparse/SparseAssign.h
  src/Sparse/SparseBlock.h
  src/Sparse/SparseCwiseBinaryOp.h
  src/Sparse/SparseCwiseUnaryOp.h
  src/Sparse/SparseDenseProduct.h
  src/Sparse/SparseDiagonalProduct.h
  src/Sparse/SparseDot.h
  src/Sparse/SparseFuzzy.h
  src/Sparse/SparseMatrixBase.h
  src/Sparse/SparseMatrix.h
  src/Sparse/SparseProduct.h
  src/Sparse/SparseRedux.h
  src/Sparse/SparseSelfAdjointView.h
  src/Sparse/SparseSparseProduct.h
  src/Sparse/SparseTranspose.h
  src/Sparse/SparseTriangularView.h
  src/Sparse/SparseUtil.h
  src/Sparse/SparseVector.h
  src/Sparse/SparseView.h
  src/Sparse/TriangularSolver.h
  src/StlSupport/details.h
  src/StlSupport/StdDeque.h
  src/StlSupport/StdList.h
  src/StlSupport/StdVector.h
  src/SVD/JacobiSVD.h
  src/SVD/UpperBidiagonalization.h
)

set(header_dirs
)
