set(headers
  cJSON.h
  vesKiwiAnimationRepresentation.h
  vesKiwiBaseApp.h
  vesKiwiBaselineImageTester.h
  vesKiwiBrainAtlasRepresentation.h
  vesKiwiCameraInteractor.h
  vesKiwiCameraSpinner.h
  vesKiwiColorMapCollection.h
  vesKiwiDataConversionTools.h
  vesKiwiDataLoader.h
  vesKiwiDataRepresentation.h
  vesKiwiFPSCounter.h
  vesKiwiImagePlaneDataRepresentation.h
  vesKiwiImageWidgetRepresentation.h
  vesKiwiPlaneWidget.h
  vesKiwiPolyDataRepresentation.h
  vesKiwiSceneRepresentation.h
  vesKiwiStreamingDataRepresentation.h
  vesKiwiTestHelper.h
  vesKiwiText2DRepresentation.h
  vesKiwiViewerApp.h
  vesKiwiWidgetInteractionDelegate.h
  vesKiwiWidgetRepresentation.h
  )

set(header_dirs
  .
  )
