SET(VES_GLOBAL_VERSION_MAJOR 1)
SET(VES_GLOBAL_VERSION_MINOR 0)
SET(VES_GLOBAL_VERSION_PATCH 0)

SET(VES_GLOBAL_VERSION_STR "${VES_GLOBAL_VERSION_MAJOR}.${VES_GLOBAL_VERSION_MINOR}.${VES_GLOBAL_VERSION_PATCH}")

SET(VES_GLOBAL_COPY_YEAR 2012)
