set(headers
  vesActor.h
  vesBackground.h
  vesBlendFunction.h
  vesBlend.h
  vesBooleanUniform.h
  vesBoundingObject.h
  vesCamera.h
  vesCullVisitor.h
  vesDepth.h
  vesEigen.h
  vesEngineUniform.h
  vesGeometryData.h
  vesGL.h
  vesGLTypes.h
  vesGroupNode.h
  vesImage.h
  vesMapper.h
  vesMaterial.h
  vesMaterialAttribute.h
  vesMath.h
  vesNode.h
  vesObject.h
  vesQNXTestDriver.h
  vesRenderData.h
  vesRenderer.h
  vesRenderLeaf.h
  vesRenderStage.h
  vesRenderState.h
  vesRenderTarget.h
  vesSetGet.h
  vesSharedPtr.h
  vesStateAttributeBits.h
  vesSourceData.h
  vesTestBase.h
  vesTestDriver.h
  vesTexture.h
  vesTransformNode.h
  vesVertexAttribute.h
  vesVertexAttributeKeys.h
  vesViewport.h
  vesVisitor.h
  vesX11TestDriver.h
)

set(header_dirs
  .
)

set(build_headers
  vesVersion.h
)

set(build_header_dirs
  .
)
