set(headers
  vesActor.h
  vesBackground.h
  vesBlendFunction.h
  vesBlend.h
  vesBooleanUniform.h
  vesBoundingObject.h
  vesCamera.h
  vesColorUniform.h
  vesCullVisitor.h
  vesDepth.h
  vesEigen.h
  vesEngineUniform.h
  vesFBO.h
  vesFBORenderTarget.h
  vesGeometryData.h
  vesGL.h
  vesGLTypes.h
  vesGroupNode.h
  vesImage.h
  vesIntegerUniform.h
  vesMapper.h
  vesMaterial.h
  vesMaterialAttribute.h
  vesMath.h
  vesModelViewUniform.h
  vesNode.h
  vesNormalMatrixUniform.h
  vesObject.h
  vesProjectionUniform.h
  vesRenderData.h
  vesRenderer.h
  vesRenderLeaf.h
  vesRenderStage.h
  vesRenderState.h
  vesRenderTarget.h
  vesRenderToTexture.h
  vesSetGet.h
  vesShader.h
  vesShaderProgram.h
  vesSharedPtr.h
  vesStateAttributeBits.h
  vesSourceData.h
  vesTexture.h
  vesTransformNode.h
  vesUniform.h
  vesVertexAttribute.h
  vesVertexAttributeKeys.h
  vesViewport.h
  vesVisitor.h
)

set(header_dirs
  .
)

set(build_headers
  vesVersion.h
)

set(build_header_dirs
  .
)
